site_name: External Secrets Operator
repo_url: https://github.com/external-secrets/external-secrets
repo_name: External Secrets Operator
site_dir: ../../site
docs_dir: ../../docs
edit_uri: ./edit/main/docs/
remote_branch: gh-pages
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.expand
  custom_dir: ../../overrides
  logo: pictures/eso-round-logo.svg
  favicon: pictures/eso-round-logo.svg
markdown_extensions:
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - pymdownx.snippets:
      base_path: docs
plugins:
  - search:
      lang: en
  - macros:
      include_dir: docs/snippets
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: pt-BR
          name: Portuguese (Brazilian)
          build: true
          nav_translations:
            Introduction: Introdução
            Getting started: Instalação
            FAQ: Perguntas frequentes
            Stability and Support: Estabilidade e suporte
            Deprecation Policy: Política de depreciação
            Components: Componentes
            Core Resources: Recursos principais
            Reference Docs: Documentação de referência
            API specification: Especificação da API
            Controller Options: Opções do controller
            Metrics: Métricas
            Guides: Guias
            Introduction: Introdução
            Extract structured data: Extrair dados estruturados
            Find Secrets by Name or Metadata: Encontrar secrets por nome ou metadata
            Rewriting Keys: Reescrevendo chaves
            Advanced Templating: Manipulando templates de forma avançada
            Kubernetes Secret Types: Tipos de Kubernetes Secrets
            "Lifecycle: ownership & deletion": "Ciclo de vida: ownership e deleção"
            Decoding Strategies: Estratégias de decoding
            Controller Classes: Classes do controller
            Operations: Operações
            Security Best Practices: Boas práticas de segurança
            Threat Model: Modelos de ameaça
            Upgrading to v1beta1: Atualizando para o v1beta1
            Using Latest Image: Usando a imagem 'latest'
            Disable Cluster Features: Desabilitar as funcionalidades à nível 'Cluster'
            Provider: Provedores
            Examples: Exemplos
            Community: Comunidade
            Contributing: Contribuindo
            Developer guide: Guia do desenvolvedor
            Contributing Process: Processo de contribuição
            Release Process: Processo de release
            Code of Conduct: Código de conduta
            External Resources: Recursos externos

copyright: |
  &copy; 2024 The external-secrets Authors.<br/>
  &copy; 2024 The Linux Foundation. All rights reserved.<br/><br/>
  The Linux Foundation has registered trademarks and uses trademarks.<br/>
  For a list of trademarks of The Linux Foundation, please see our <a href="https://www.linuxfoundation.org/trademark-usage/">Trademark Usage page</a>.
extra:
  alternate:
    - name: English
      link: /
      lang: en
    - name: Portuguese (Brazilian)
      link: /pt-BR/
      lang: pt-BR
  version:
    provider: mike
  analytics:
    provider: google
    property: G-QP38TD8K7V
nav:
  - Introduction:
    - Introduction: index.md
    - Overview: introduction/overview.md
    - Getting started: introduction/getting-started.md
    - FAQ: introduction/faq.md
    - Stability and Support: introduction/stability-support.md
    - Deprecation Policy: introduction/deprecation-policy.md
  - API:
    - Components: api/components.md
    - Core Resources:
      - ExternalSecret: api/externalsecret.md
      - SecretStore: api/secretstore.md
      - ClusterSecretStore: api/clustersecretstore.md
      - ClusterExternalSecret: api/clusterexternalsecret.md
      - PushSecret: api/pushsecret.md
    - Generators:
      - "api/generator/index.md"
      - Azure Container Registry: api/generator/acr.md
      - AWS Elastic Container Registry: api/generator/ecr.md
      - Google Container Registry: api/generator/gcr.md
      - Vault Dynamic Secret: api/generator/vault.md
      - Password: api/generator/password.md
      - Fake: api/generator/fake.md
      - Webhook: api/generator/webhook.md
      - Github: api/generator/github.md
    - Reference Docs:
      - API specification: api/spec.md
      - Controller Options: api/controller-options.md
      - Metrics: api/metrics.md
  - Guides:
    - Introduction: guides/introduction.md
    - External Secrets:
      - Extract structured data: guides/all-keys-one-secret.md
      - Find Secrets by Name or Metadata: guides/getallsecrets.md
      - Rewriting Keys: guides/datafrom-rewrite.md
      - Advanced Templating:
        - v2: guides/templating.md
        - v1: guides/templating-v1.md
      - Kubernetes Secret Types: guides/common-k8s-secret-types.md
      - "Lifecycle: ownership & deletion": guides/ownership-deletion-policy.md
      - Decoding Strategies: guides/decoding-strategy.md
      - Controller Classes: guides/controller-class.md
    - Generators: guides/generator.md
    - Push Secrets: guides/pushsecrets.md
    - Operations:
      - Multi Tenancy: guides/multi-tenancy.md
      - Security Best Practices: guides/security-best-practices.md
      - Threat Model: guides/threat-model.md
      - Upgrading to v1beta1: guides/v1beta1.md
      - Using Latest Image: guides/using-latest-image.md
      - Disable Cluster Features: guides/disable-cluster-features.md
  - Provider:
    - AWS Secrets Manager: provider/aws-secrets-manager.md
    - AWS Parameter Store: provider/aws-parameter-store.md
    - Azure Key Vault: provider/azure-key-vault.md
    - Chef: provider/chef.md
    - CyberArk Conjur: provider/conjur.md
    - Google Cloud Secret Manager: provider/google-secrets-manager.md
    - HashiCorp Vault: provider/hashicorp-vault.md
    - Kubernetes: provider/kubernetes.md
    - IBM Secrets Manager: provider/ibm-secrets-manager.md
    - Akeyless: provider/akeyless.md
    - Yandex Certificate Manager: provider/yandex-certificate-manager.md
    - Yandex Lockbox: provider/yandex-lockbox.md
    - Alibaba Cloud: provider/alibaba.md
    - GitLab Variables: provider/gitlab-variables.md
    - Oracle Vault: provider/oracle-vault.md
    - 1Password Secrets Automation: provider/1password-automation.md
    - Webhook: provider/webhook.md
    - Fake: provider/fake.md
    - senhasegura DevOps Secrets Management (DSM): provider/senhasegura-dsm.md
    - Doppler: provider/doppler.md
    - Keeper Security: provider/keeper-security.md
    - Cloak End 2 End Encrypted Secrets: provider/cloak.md
    - Scaleway: provider/scaleway.md
    - Delinea: provider/delinea.md
    - Passbolt: provider/passbolt.md
    - Pulumi ESC: provider/pulumi.md
    - Onboardbase: provider/onboardbase.md
    - Password Depot: provider-passworddepot.md
    - Fortanix: provider/fortanix.md
  - Examples:
    - FluxCD: examples/gitops-using-fluxcd.md
    - Anchore Engine: examples/anchore-engine-credentials.md
    - Jenkins: examples/jenkins-kubernetes-credentials.md
    - BitWarden: examples/bitwarden.md
  - Community:
    - Contributing:
      - Developer guide: contributing/devguide.md
      - Contributing Process: contributing/process.md
      - Release Process: contributing/release.md
      - Code of Conduct: contributing/coc.md
      - Roadmap: contributing/roadmap.md
    - External Resources:
      - Talks: eso-talks.md
      - Demos: eso-demos.md
      - Blogs: eso-blogs.md
  - References:
    - API specification: spec.md
